parameters:
    # System Location IDs
    ezsettings.default.location_ids.content_structure: 2
    ezsettings.default.location_ids.media: 43
    ezsettings.default.location_ids.users: 5

    # Pagination limits
    ezsettings.default.pagination.search_limit: 10
    ezsettings.default.pagination.trash_limit: 10
    ezsettings.default.pagination.section_limit: 10
    ezsettings.default.pagination.language_limit: 10
    ezsettings.default.pagination.role_limit: 10
    ezsettings.default.pagination.content_type_group_limit: 10
    ezsettings.default.pagination.content_type_limit: 10
    ezsettings.default.pagination.role_assignment_limit: 10
    ezsettings.default.pagination.policy_limit: 10
    ezsettings.default.pagination.version_draft_limit: 5
    ezsettings.default.pagination.content_system_url_limit: 5
    ezsettings.default.pagination.content_custom_url_limit: 5
    ezsettings.default.pagination.content_role_limit: 5
    ezsettings.default.pagination.content_policy_limit: 5
    ezsettings.default.pagination.bookmark_limit: 10
    ezsettings.default.pagination.notification_limit: 5
    ezsettings.default.pagination.user_settings_limit: 10
    ezsettings.default.pagination.content_draft_limit: 10

    # Security
    ezsettings.default.security.token_interval_spec: PT1H

    # Subitems Module
    ezsettings.default.subitems_module.limit: 10

    # Universal Discovery Widget Module
    ezsettings.default.universal_discovery_widget_module.default_location_id: 1

    # User identifier
    ezsettings.default.user_content_type_identifier: ['user']

    # User Group identifier
    ezsettings.default.user_group_content_type_identifier: ['user_group']

    # Subtree Operations
    ezsettings.default.subtree_operations.copy_subtree.limit: 100

    # Notifications
    ezsettings.default.notifications.error.timeout: 0
    ezsettings.default.notifications.warning.timeout: 0
    ezsettings.default.notifications.success.timeout: 5000
    ezsettings.default.notifications.info.timeout: 0

    # Views
    ezsettings.default.content_translate_view: {}
    ezsettings.admin_group.user_settings.templates.list: "EzPlatformAdminUiBundle:user/settings:list.html.twig"
    ezsettings.admin_group.user_settings.templates.update: "EzPlatformAdminUiBundle:user/settings:update.html.twig"
    ezsettings.admin_group.user_change_password.templates.form: "EzPlatformAdminUiBundle:user_profile:change_user_password.html.twig"
    ezsettings.admin_group.user_forgot_password.templates.form: "EzPlatformAdminUiBundle:security/forgot_user_password:index.html.twig"
    ezsettings.admin_group.user_forgot_password_success.templates.form: "EzPlatformAdminUiBundle:security/forgot_user_password:success.html.twig"
    ezsettings.admin_group.user_forgot_password_login.templates.form: "EzPlatformAdminUiBundle:security/forgot_user_password:with_login.html.twig"
    ezsettings.admin_group.user_forgot_password.templates.mail: "EzPlatformAdminUiBundle:security/mail:forgot_user_password.html.twig"
    ezsettings.admin_group.user_reset_password.templates.form: "EzPlatformAdminUiBundle:security/reset_user_password:index.html.twig"
    ezsettings.admin_group.user_reset_password.templates.invalid_link: "EzPlatformAdminUiBundle:security/reset_user_password:invalid_link.html.twig"
    ezsettings.admin_group.user_reset_password.templates.success: "EzPlatformAdminUiBundle:security/reset_user_password:success.html.twig"

    # Content Tree Module
    ezsettings.default.content_tree_module.load_more_limit: 30
    ezsettings.default.content_tree_module.children_load_max_limit: 200
    ezsettings.default.content_tree_module.tree_max_depth: 10
    ezsettings.default.content_tree_module.allowed_content_types: []
    ezsettings.default.content_tree_module.ignored_content_types: []
    ezsettings.default.content_tree_module.tree_root_location_id: ~

