parameters:
    # System Location IDs
    ezsettings.default.location_ids.content_structure: 2
    ezsettings.default.location_ids.media: 43
    ezsettings.default.location_ids.users: 5

    # Pagination limits
    ezsettings.default.pagination.search_limit: 10
    ezsettings.default.pagination.trash_limit: 10
    ezsettings.default.pagination.section_limit: 10
    ezsettings.default.pagination.language_limit: 10
    ezsettings.default.pagination.role_limit: 10
    ezsettings.default.pagination.content_type_group_limit: 10
    ezsettings.default.pagination.content_type_limit: 10
    ezsettings.default.pagination.role_assignment_limit: 10
    ezsettings.default.pagination.policy_limit: 10
    ezsettings.default.pagination.version_draft_limit: 5

    # Security
    ezsettings.default.security.token_interval_spec: PT1H

    # Subitems Module
    ezsettings.default.subitems_module.limit: 10

    # Universal Discovery Widget Module
    ezsettings.default.universal_discovery_widget_module.default_location_id: 1
