system:
    default:
        universal_discovery_widget_module:
            default_location_id: 1
            configuration:
                default:
                    multiple: true
                    active_tab: 'browse'
                    starting_location_id: 1
                    visible_tabs: []
                    selected_items_limit: 0
                    containers_only: false
                    allowed_content_types: []
                    content_on_the_fly:
                        allowed_languages: []
                        allowed_content_types: []
                        allowed_locations: []
                        preselected_language: null
                        preselected_content_type: null
                        preselected_location: null
                    search:
                        results_per_page: 10
                        limit: 50
                sunpietro:
                    multiple: false
                    active_tab: 'create'
                    starting_location_id: 207
                    content_on_the_fly:
                        allowed_languages: ['eng-GB', 'ger-DE']
                        allowed_content_types: ['blog_post', 'article']
                        preselected_language: 'ger-DE'
                        preselected_content_type: 'article'
                        preselected_location: 208

                create:
                    active_tab: 'create'
                    visible_tabs: ['create']
                    multiple: false
                    starting_location_id: 1
                single:
                    multiple: false
                multiple:
                    multiple: true
                single_container:
                    multiple: false
                    containers_only: true
                richtext_embed:
                    multiple: false
                richtext_embed_image:
                    multiple: false
                    content_on_the_fly:
                        allowed_content_types: ['image']
                image_asset:
                    multiple: false
                    visible_tabs: ['browse', 'search', 'bookmarks']
                single_user:
                    multiple: false
                multiple_user:
                    multiple: true
                single_user_group:
                    allowed_content_types: ['user_group']
                    multiple: false
                multiple_user_group:
                    allowed_content_types: ['user_group']
                    multiple: true
