system:
    admin_group:
        user:
            login_template: '@ezdesign/Security/login.html.twig'

        content_view:
            full:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@ezdesign/content/location_view.html.twig'
                    match: true
            preview_ezobjectrelationlist_row:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@ezdesign\field_type\preview\ezobjectrelationlist_row.html.twig'
                    match: true
            preview_ezimageasset:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@ezdesign\field_type\preview\ezimageasset.html.twig'
                    match: true

        content_edit_view:
            full:
                ezplatform_admin_ui:
                    template: '@ezdesign/content/content_edit/content_edit.html.twig'
                    match: true
                    params:
                        viewbaseLayout: '@ezdesign/layout.html.twig'

        content_create_view:
            full:
                ezplatform_admin_ui:
                    template: '@ezdesign/content/content_edit/content_create.html.twig'
                    match: true
                    params:
                        viewbaseLayout: '@ezdesign/layout.html.twig'

        content_translate_view:
            full:
                ezplatform_admin_ui:
                    template: '@ezdesign/content/content_edit/content_edit.html.twig'
                    match: true
                    params:
                        viewbaseLayout: '@ezdesign/layout.html.twig'

        user_settings_update_view:
            full:
                ezplatform_admin_ui_datetime_format:
                    template: '@ezdesign/user/settings/update_datetime_format.html.twig'
                    match:
                        Identifier: [full_datetime_format, short_datetime_format]

        fielddefinition_edit_templates:
            - { template: '@ezdesign/admin/content_type/field_types.html.twig', priority: 10 }
