system:
    admin_group:
        user:
            login_template: '@EzPlatformAdminUi/Security/login.html.twig'
        content_view:
            full:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@EzPlatformAdminUi/content/locationview.html.twig'
                    match: true
            preview_ezobjectrelationlist_row:
                default:
                    controller: 'EzPlatformAdminUiBundle:ContentView:locationView'
                    template: '@EzPlatformAdminUi\fieldtypes\preview\ezobjectrelationlist_row.html.twig'
                    match: true

