services:
    app.my_tabs.custom_group:
        parent: Ibexa\AdminUi\Component\TabsComponent
        arguments:
            $template: '@@ezdesign/ui/tab/url_management.html.twig'
            $groupIdentifier: 'link-manager'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'link-manager-block' }

    Ibexa\AdminUi\Tab\URLManagement\URLWildcardsTab:
        class: Ibexa\AdminUi\Tab\URLManagement\URLWildcardsTab
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab
        tags:
            - { name: ezplatform.tab, group: 'link-manager' }

    Ibexa\AdminUi\Tab\URLManagement\LinkManagerTab:
        class: Ibexa\AdminUi\Tab\URLManagement\LinkManagerTab
        parent: Ibexa\Contracts\AdminUi\Tab\AbstractTab
        tags:
            - { name: ezplatform.tab, group: 'link-manager' }
