imports:
    - { resource: services/components/content/edit.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Ibexa\AdminUi\Component\Registry:
        public: false

    Ibexa\AdminUi\Component\TwigComponent:
        abstract: true
        lazy: true
        arguments:
            $parameters: []

    Ibexa\AdminUi\Component\TabsComponent:
        abstract: true
        lazy: true
        arguments:
            $template: '@@ezdesign/ui/tab/default.html.twig'

    Ibexa\AdminUi\Component\ScriptComponent:
        abstract: true
        lazy: true

    Ibexa\AdminUi\Component\LinkComponent:
        abstract: true
        lazy: true

    Ibexa\Bundle\AdminUi\Templating\Twig\ComponentExtension:
        tags:
            - { name: twig.extension }

    Ibexa\AdminUi\Component\Renderer\DefaultRenderer:
        public: false

    Ibexa\Contracts\AdminUi\Component\Renderer\RendererInterface: '@Ibexa\AdminUi\Component\Renderer\DefaultRenderer'
