services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUiBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    EzSystems\EzPlatformAdminUiBundle\Controller\ContentTypeController:
        public: true
        arguments:
            $contentTypeActionDispatcher: '@ezrepoforms.action_dispatcher.content_type'
            $languages: '$languages$'
            $defaultPaginationLimit: '$pagination.content_type_limit$'

    EzSystems\EzPlatformAdminUiBundle\Controller\ContentTypeGroupController:
        public: true
        arguments:
            $languages: '$languages$'
            $defaultPaginationLimit: '$pagination.content_type_group_limit$'


    EzSystems\EzPlatformAdminUiBundle\Controller\SearchController:
        public: true
        arguments:
            $defaultPaginationLimit: '$pagination.search_limit$'

    EzSystems\EzPlatformAdminUiBundle\Controller\ContentController:
        public: true
        arguments:
            $defaultSiteaccess: '%ezpublish.siteaccess.default%'

    EzSystems\EzPlatformAdminUiBundle\Controller\TrashController:
        public: true
        arguments:
            $defaultPaginationLimit: '$pagination.trash_limit$'

    EzSystems\EzPlatformAdminUiBundle\Controller\SectionController:
        public: true
        arguments:
            $defaultPaginationLimit: '$pagination.section_limit$'

    EzSystems\EzPlatformAdminUiBundle\Controller\LanguageController:
        public: true
        arguments:
            $defaultPaginationLimit: '$pagination.language_limit$'

    EzSystems\EzPlatformAdminUiBundle\Controller\RoleController:
        public: true
        arguments:
            $defaultPaginationLimit: '$pagination.role_limit$'
