services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUiBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]
            - [performAccessCheck, []]

    EzSystems\EzPlatformAdminUiBundle\Controller\ContentTypeController:
        public: true
        arguments:
            $contentTypeActionDispatcher: '@ezrepoforms.action_dispatcher.content_type'
            $languages: '$languages$'

    EzSystems\EzPlatformAdminUiBundle\Controller\ContentTypeGroupController:
        public: true
        arguments:
            $languages: '$languages$'


    EzSystems\EzPlatformAdminUiBundle\Controller\SearchController:
        public: true
        arguments:
            $defaultLimit: '$search_limit$'
