services:
  EzSystems\EzPlatformAdminUi\REST\Input\Parser\BulkOperation:
      parent: ezpublish_rest.input.parser
      tags:
        - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.BulkOperation }

  EzSystems\EzPlatformAdminUi\REST\Input\Parser\Operation:
      parent: ezpublish_rest.input.parser
      tags:
        - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.internal.Operation }

  EzSystems\EzPlatformAdminUi\REST\Output\ValueObjectVisitor\BulkOperationResponse:
      parent: ezpublish_rest.output.value_object_visitor.base
      tags:
        - { name: ezpublish_rest.output.value_object_visitor, type: EzSystems\EzPlatformAdminUi\REST\Value\BulkOperationResponse }

  #
  # Content Tree
  #

  EzSystems\EzPlatformAdminUi\REST\Input\Parser\ContentTree\LoadSubtreeRequestNode:
    parent: ezpublish_rest.input.parser
    tags:
      - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentTreeLoadSubtreeRequestNode }

  EzSystems\EzPlatformAdminUi\REST\Input\Parser\ContentTree\LoadSubtreeRequest:
    parent: ezpublish_rest.input.parser
    tags:
      - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentTreeLoadSubtreeRequest }

  EzSystems\EzPlatformAdminUi\REST\Output\ValueObjectVisitor\ContentTree\Node:
      parent: ezpublish_rest.output.value_object_visitor.base
      tags:
          - { name: ezpublish_rest.output.value_object_visitor, type: EzSystems\EzPlatformAdminUi\REST\Value\ContentTree\Node }

  EzSystems\EzPlatformAdminUi\REST\Output\ValueObjectVisitor\ContentTree\Root:
      parent: ezpublish_rest.output.value_object_visitor.base
      tags:
          - { name: ezpublish_rest.output.value_object_visitor, type: EzSystems\EzPlatformAdminUi\REST\Value\ContentTree\Root }

  #
  # Content type create/edit form
  #
  Ibexa\AdminUi\REST\Input\Parser\ContentType\FieldDefinitionCreate:
    parent: ezpublish_rest.input.parser
    tags:
      - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentTypFieldDefinitionCreate }

  Ibexa\AdminUi\REST\Input\Parser\ContentType\FieldDefinitionDelete:
    parent: ezpublish_rest.input.parser
    tags:
      - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentTypeFieldDefinitionDelete }

  Ibexa\AdminUi\REST\Input\Parser\ContentType\FieldDefinitionReorder:
    parent: ezpublish_rest.input.parser
    tags:
      - { name: ezpublish_rest.input.parser, mediaType: application/vnd.ez.api.ContentTypeFieldDefinitionReorder }

  EzSystems\EzPlatformAdminUi\REST\Security\NonAdminRESTRequestMatcher:
      arguments:
          $siteAccessGroups: '%ezpublish.siteaccess.groups%'
