services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    EzSystems\EzPlatformAdminUi\View\Builder\ContentTranslateViewBuilder:
        arguments:
            $repository: '@ezpublish.api.repository'
            $viewConfigurator: '@ezpublish.view.configurator'
            $viewParametersInjector: '@ezpublish.view.view_parameters.injector.dispatcher'
            $contentActionDispatcher: '@ezrepoforms.action_dispatcher.content'

    EzSystems\EzPlatformAdminUi\View\Provider\ContentTranslateView\Configured:
        arguments:
            $matcherFactory: '@ezplatform.admin_ui.view.content_translate.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\ContentTranslateView, priority: 10 }

    ezplatform.admin_ui.view.content_translate.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            $relativeNamespace: 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setContainer, ['@service_container']]
            - [setMatchConfig, ['$content_translate_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\ContentTranslateViewFilter:
        tags:
            - { name: kernel.event_subscriber }

    # Relation view
    EzSystems\EzPlatformAdminUi\View\Builder\RelationViewBuilder:
        arguments:
            $viewConfigurator: '@ezpublish.view.configurator'
            $viewParametersInjector: '@ezpublish.view.view_parameters.injector.dispatcher'

    EzSystems\EzPlatformAdminUi\View\Provider\RelationView\Configured:
        arguments:
            $matcherFactory: '@ezplatform.admin_ui.view.relation.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\RelationView, priority: 10 }

    ezplatform.admin_ui.view.relation.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            $relativeNamespace: 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setContainer, ['@service_container']]
            - [setMatchConfig, ['$relation_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\RelationViewFilter:
        tags:
            - { name: kernel.event_subscriber }
