services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # ContentTranslateView
    #
    EzSystems\EzPlatformAdminUi\View\Builder\ContentTranslateViewBuilder:
        arguments:
            $repository: '@ezpublish.api.repository'
            $viewConfigurator: '@ezpublish.view.configurator'
            $viewParametersInjector: '@ezpublish.view.view_parameters.injector.dispatcher'
            $contentActionDispatcher: '@EzSystems\EzPlatformAdminUi\Form\ActionDispatcher\ContentDispatcher'

    EzSystems\EzPlatformAdminUi\View\Provider\ContentTranslateView\Configured:
        arguments:
            $matcherFactory: '@ezplatform.admin_ui.view.content_translate.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\ContentTranslateView, priority: 10 }

    ezplatform.admin_ui.view.content_translate.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setMatchConfig, ['$content_translate_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\ContentTranslateViewFilter:
        tags:
            - { name: kernel.event_subscriber }

    #
    # ContentEditView
    #
    EzSystems\EzPlatformAdminUi\View\Builder\ContentEditViewBuilder:
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'
            - '$content_edit.templates.edit$'
            - '@EzSystems\EzPlatformAdminUi\Form\ActionDispatcher\ContentDispatcher'

    EzSystems\EzPlatformAdminUi\View\Provider\ContentEditView\Configured:
        arguments:
            - '@ezplatform.repository_forms.content_edit_view.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\ContentEditView, priority: 10 }

    ezplatform.repository_forms.content_edit_view.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setMatchConfig, ['$content_edit_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\ContentEditViewFilter:
        arguments:
            - '@ezpublish.api.service.content'
            - '@ezpublish.api.service.content_type'
        tags:
            - { name: kernel.event_subscriber }

    #
    # ContentCreateView
    #
    EzSystems\EzPlatformAdminUi\View\Builder\ContentCreateViewBuilder:
        arguments:
            - '@ezpublish.api.repository'
            - '@ezpublish.view.configurator'
            - '@ezpublish.view.view_parameters.injector.dispatcher'
            - '$content_edit.templates.create$'
            - '@EzSystems\EzPlatformAdminUi\Form\ActionDispatcher\ContentDispatcher'

    EzSystems\EzPlatformAdminUi\View\Provider\ContentCreateView\Configured:
        arguments:
            - '@ezplatform.repository_forms.content_create_view.matcher_factory'
        tags:
            - {name: ezpublish.view_provider, type: 'EzSystems\EzPlatformAdminUi\View\ContentCreateView', priority: 10}

    ezplatform.repository_forms.content_create_view.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setMatchConfig, ['$content_create_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\ContentCreateViewFilter:
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content_type'
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\Limitation\Templating\LimitationBlockRenderer:
        arguments:
            - '@ezrepoforms.limitation_value_mapper.registry'
            - '@twig'
        calls:
            - ['setLimitationValueResources', [ '$limitation_value_templates$' ]]
