services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # ContentTranslateView
    #
    EzSystems\EzPlatformAdminUi\View\Builder\ContentTranslateViewBuilder:
        arguments:
            $repository: '@ezpublish.api.repository'
            $viewConfigurator: '@ezpublish.view.configurator'
            $viewParametersInjector: '@ezpublish.view.view_parameters.injector.dispatcher'
            $contentActionDispatcher: '@ezplatform.content_forms.action_dispatcher.content'
        tags:
            - { name: ibexa.view_builder }

    EzSystems\EzPlatformAdminUi\View\Provider\ContentTranslateView\Configured:
        arguments:
            $matcherFactory: '@ezplatform.admin_ui.view.content_translate.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\ContentTranslateView, priority: 10 }

    ezplatform.admin_ui.view.content_translate.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'

    ezpublish.content_translate.matcher_factory.dynamically_configured:
        class: eZ\Publish\Core\MVC\Symfony\Matcher\DynamicallyConfiguredMatcherFactoryDecorator
        decorates: ezplatform.admin_ui.view.content_translate.matcher_factory
        arguments:
            $innerConfigurableMatcherFactory: '@ezpublish.content_view.matcher_factory.dynamically_configured.inner'
            $configResolver: '@ezpublish.config.resolver'
            $parameterName: content_translate_view

    EzSystems\EzPlatformAdminUi\View\Filter\ContentTranslateViewFilter:
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\Limitation\Templating\LimitationBlockRenderer:
        arguments:
            $valueMapperRegistry: '@ezplatform.content_forms.limitation_value_mapper.registry'
            $twig: '@twig'
            $configResolver: '@ezpublish.config.resolver'

    EzSystems\EzPlatformAdminUi\View\Filter\AdminSearchViewFilter:
        decorates: Ibexa\Platform\Search\View\SearchViewFilter
        arguments:
            $configResolver: '@ezpublish.config.resolver'
            $formFactory: '@Symfony\Component\Form\FormFactoryInterface'
            $sectionService: '@ezpublish.api.service.section'
            $contentTypeService: '@ezpublish.api.service.content_type'
            $siteAccessGroups: '%ezpublish.siteaccess.groups%'
            $innerFilter: '@EzSystems\EzPlatformAdminUi\View\Filter\AdminSearchViewFilter.inner'
            $urlGenerator: '@router'
        tags:
            - { name: kernel.event_subscriber }
