services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    #
    # ContentTranslateView
    #
    EzSystems\EzPlatformAdminUi\View\Builder\ContentTranslateViewBuilder:
        arguments:
            $repository: '@ezpublish.api.repository'
            $viewConfigurator: '@ezpublish.view.configurator'
            $viewParametersInjector: '@ezpublish.view.view_parameters.injector.dispatcher'
            $contentActionDispatcher: '@ezplatform.content_forms.action_dispatcher.content'

    EzSystems\EzPlatformAdminUi\View\Provider\ContentTranslateView\Configured:
        arguments:
            $matcherFactory: '@ezplatform.admin_ui.view.content_translate.matcher_factory'
        tags:
            - { name: ezpublish.view_provider, type: EzSystems\EzPlatformAdminUi\View\ContentTranslateView, priority: 10 }

    ezplatform.admin_ui.view.content_translate.matcher_factory:
        class: '%ezpublish.view.matcher_factory.class%'
        arguments:
            - '@eZ\Bundle\EzPublishCoreBundle\Matcher\ViewMatcherRegistry'
            - '@ezpublish.api.repository'
            - 'eZ\Publish\Core\MVC\Symfony\Matcher\ContentBased'
        calls:
            - [setMatchConfig, ['$content_translate_view$']]

    EzSystems\EzPlatformAdminUi\View\Filter\ContentTranslateViewFilter:
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformAdminUi\Limitation\Templating\LimitationBlockRenderer:
        arguments:
            $valueMapperRegistry: '@ezplatform.content_forms.limitation_value_mapper.registry'
            $twig: '@twig'
            $configResolver: '@ezpublish.config.resolver'
